service: lambda-saga

custom:
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: 
        - arn:aws:dynamodb:${self:custom.region}:*:table/users
        - arn:aws:dynamodb:${self:custom.region}:*:table/orders
        - arn:aws:dynamodb:${self:custom.region}:*:table/orderRow
        - arn:aws:dynamodb:${self:custom.region}:*:table/stock
        - arn:aws:dynamodb:${self:custom.region}:*:table/payments

functions:
  cancel-payment:
    handler: functions/cancel-payment.handler
    events:
      - http:
          path: /payment/cancelPayment/{user_id}/{order_id}
          method: POST
          integration: lambda
          private: false
          request:
            parameters:
              paths:
                user_id: true
                order_id: true

  pay:
    handler: functions/pay.handler
    events:
      - http:
          path: /payment/pay/{user_id}/{order_id}
          method: POST
          integration: lambda
          private: false
          request:
            parameters:
              paths:
                user_id: true
                order_id: true

  payment-status:
    handler: functions/payment-status.handler
    events:
      - http:
          path: /payment/status/{order_id}
          method: GET
          integration: lambda
          private: false
          request:
            parameters:
              paths:
                order_id: true

  remove-payment:
    handler: functions/remove-payment.handler
    events:
      - http:
          path: /payment/remove/{order_id}
          method: DELETE
          integration: lambda
          private: false
          request:
            parameters:
              paths:
                order_id: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: credit
            AttributeType: N
          - AttributeName: isDeleted
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orders
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: totalPrice
            AttributeType: N
          - AttributeName: user_ID
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    orderRowTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orderRow 
        AttributeDefinitions:
          - AttributeName: order_ID
            AttributeType: S
          - AttributeName: item_ID
            AttributeType: S
          - AttributeName: quantity
            AttributeType: N
        KeySchema:
          - AttributeName: order_ID
            KeyType: HASH
          - AttributeName: item_ID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    stockTable:
       Type: AWS::DynamoDB::Table
       Properties:
         TableName: stock
         AttributeDefinitions:
           - AttributeName: item_ID
             AttributeType: S
           - AttributeName: quantity
             AttributeType: N
           - AttributeName: price
             AttributeType: N
         KeySchema:
           - AttributeName: item_ID
             KeyType: HASH
         ProvisionedThroughput:
           ReadCapacityUnits: 1
           WriteCapacityUnits: 1

    paymentTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: payments 
          AttributeDefinitions:
            - AttributeName: order_ID
              AttributeType: S
            - AttributeName: isPaid
              AttributeType: N
          KeySchema:
            - AttributeName: order_ID
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
