service: saga-service 

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10

  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:*:*:*"
    - Effect: "Allow"
      Action: 
        - "states:ListStateMachines"
        - "states:StartExecution"
        - "states:GetExecutionHistory"
      Resource: "arn:aws:states:*:*:*"

stepFunctions:
  stateMachines: 
    FindOrder:
      name: FindOrderStateMachine
      events:
        - http:
            path: orders/find/{order_id}
            method: GET
            request:
              template:
                application/json: |                  
                  {
                    "input" : "{ \"order_id\": \"$input.params('order_id')\" }",
                    "stateMachineArn":"arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:FindOrderStateMachine"
                  }
      definition:
        Comment: "Applying the Saga pattern for the find endpoint of the order microservice"
        StartAt: PaymentStatus
        States:
          PaymentStatus:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:payment-service-${opt:stage}-payment-status"
            Catch:
            - ErrorEquals: ["States.ALL"]
              ResultPath: "$.PaymentStatusError"
              Next: Fail
            ResultPath: "$.PaymentStatusResult"
            Next: PaymentResultStatusCode
          PaymentResultStatusCode:
            Type: Choice
            Choices:
            - Or:
              - Variable: "$.PaymentStatusResult.statusCode"
                NumericEquals: 200
              - Variable: "$.PaymentStatusResult.statusCode"
                NumericEquals: 404
              Next: OrderStatus
            Default: Fail
          OrderStatus:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:orders-microservice-${opt:stage}-find-order"
            Catch:
            - ErrorEquals: ["States.ALL"]
              ResultPath: "$.OrderStatusError"
              Next: Fail
            ResultPath: "$.OrderStatusResult"
            End: true
          Fail:
            Type: Fail
End: true