service: saga-service 

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10

  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:*:*:*"
    - Effect: "Allow"
      Action: 
        - "states:ListStateMachines"
        - "states:StartExecution"
        - "states:GetExecutionHistory"
      Resource: "arn:aws:states:*:*:*"

stepFunctions:
  stateMachines: 
    FindOrder:
      name: FindOrderStateMachine
      events:
        - http:
            path: orders/find/{order_id}
            method: GET
            private: false
            request:
              template:
                application/json: |                  
                  {
                    "input" : "{ \"order_id\": \"$input.params('order_id')\" }",
                    "stateMachineArn":"arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:FindOrderStateMachine"
                  }
              parameters:
                paths:
                  order_id: true
      definition:
        Comment: "Applying the Saga pattern for the find endpoint of the order microservice"
        StartAt: PaymentStatus
        States:
          PaymentStatus:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:payment-microservice-${opt:stage}-payment-status"
            Catch:
            - ErrorEquals: ["States.ALL"]
              ResultPath: "$.PaymentStatusError"
              Next: Fail
            ResultPath: "$.PaymentStatusResult"
            Next: PaymentResultStatusCode
          PaymentResultStatusCode:
            Type: Choice
            Choices:
            - Or:
              - Variable: "$.PaymentStatusResult.statusCode"
                NumericEquals: 200
              - Variable: "$.PaymentStatusResult.statusCode"
                NumericEquals: 404
              Next: OrderStatus
            Default: Fail
          OrderStatus:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:orders-microservice-${opt:stage}-find-order"
            Catch:
            - ErrorEquals: ["States.ALL"]
              ResultPath: "$.OrderStatusError"
              Next: Fail
            ResultPath: "$.OrderStatusResult"
            End: true
          Fail:
            Type: Fail
    OrderAddItem:
      name: OrderAddItemStateMachine
      events:
        - http:
            path: orders/addItem/{order_id}/{item_id}
            method: POST
            private: false
            request:
              template:
                application/json: |                  
                  {
                    "input" : "{ \"order_id\": \"$input.params('order_id')\", \"item_id\": \"$input.params('item_id')\" }",
                    "stateMachineArn":"arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:OrderAddItemStateMachine"
                  }
              parameters:
                paths:
                  order_id: true
                  item_id: true
      definition:
        Comment: "Applying the Saga pattern for the addItem endpoint of the order microservice"
        StartAt: StockAvailability
        States:
          StockAvailability:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:stock-microservice-${opt:stage}-stock-availability"
            Catch:
            - ErrorEquals: ["States.ALL"]
              ResultPath: "$.StockAvailabilityError"
              Next: Fail
            ResultPath: "$.StockAvailabilityResult"
            Next: StockAvailabilityStatusCode
          StockAvailabilityStatusCode:
            Type: Choice
            Choices:
            - Or:
              - Variable: "$.StockAvailabilityResult.statusCode"
                NumericEquals: 200
              - Variable: "$.StockAvailabilityResult.statusCode"
                NumericEquals: 404
              Next: OrderAddItem
            Default: Fail
          OrderAddItem:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:orders-microservice-${opt:stage}-add-item"
            Catch:
            - ErrorEquals: ["States.ALL"]
              ResultPath: "$.OrderAddItemError"
              Next: Fail
            ResultPath: "$.OrderAddItemResult"
            End: true
          Fail:
            Type: Fail
            
End: true