Name: locust

image:
  repository: greenbirdit/locust
  tag: 0.9.0
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  name: master-web
  type: NodePort
  externalPort: 8089
  internalPort: 8089
  nodePort: 0
  annotations: {}
  extraLabels: {}
master:
  config:
    target-host: https://6ull6qibde.execute-api.us-east-1.amazonaws.com/dev
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
worker:
  config:

    # Optional parameter to use an existing configmap instead of deploying one with the Chart
    #configmapName: locust-testt

    # all files from specified configmap (or tasks folder) are mounted under `/locust-tasks`
    locust-script: "/locust-tasks/tasks.py"
  replicaCount: 8
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi
