service: postgres-stock-microservice

package:
  excludeDevDependencies: false
  
custom:
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: dev
  region: us-east-1
  environment:
    PGHOST: webdatamanagementstock.ce28ceiqtpkp.us-east-1.rds.amazonaws.com
    PGUSER: PLACEHOLDER-USERNAME
    PGDATABASE: PLACEHOLDER-DBNAME
    PGPASSWORD: PLACEHOLDER-PWD
    PGPORT: 5432

functions:
  # -----------------------------
  # Stock functions
  # -----------------------------
  stock-availability:
    handler: functions/stock-availability.handler
    events:
      - http:
          path: /stock/availability/{item_id}
          method: GET
          integration: lambda
          private: false
          request:
            parameters:
              paths:
                item_id: true

  stock-subtract:
    handler: functions/stock-subtract.handler
    events:
      - http:
          path: /stock/subtract/{order_id}
          method: POST
          integration: lambda
          private: false
          request:
            parameters:
              paths:
                order_id: true

  stock-add:
    handler: functions/stock-add.handler
    events:
      - http:
          path: /stock/add/{item_id}/{number}
          method: POST
          integration: lambda
          private: false
          request:
            parameters:
              paths:
                item_id: true
                number: true

  stock-return:
    handler: functions/stock-return.handler
    events:
      - http:
          path: /stock/return/{order_id}
          method: POST
          integration: lambda
          private: false
          request:
            parameters:
              paths:
                order_id: true

  stock-create:
    handler: functions/stock-create.handler
    events:
      - http:
          path: /stock/item/create/
          method: POST
          integration: lambda
          private: false

resources:
  Resources:
    StockDB:
      Type: AWS::RDS::DBInstance
      Properties: 
        Engine: Postgres
        EngineVersion: 10.6
        DBInstanceIdentifier: "PLACEHOLDER-DBID"    # case insensitive
        DBName: "PLACEHOLDER-DBNAME"                # case sensitive
        MasterUsername: "PLACEHOLDER-USERNAME"
        MasterUserPassword: "PLACEHOLDER-PWD"
        DBInstanceClass: "PLACEHOLDER-DBINSTANCE-CLASS"
        AllocatedStorage: 20
        Port: 5432
        PubliclyAccessible: true
